# Dockerfile.tests
FROM node:14

# Install Chrome and dependencies
RUN apt-get update && \
    apt-get install -y wget unzip xvfb libfontconfig && \
    wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    dpkg -i google-chrome*.deb || apt-get -f install -y && \
    rm google-chrome*.deb

# Set working directory
WORKDIR /tests

# Copy test files into the container
COPY tests/selenium /tests

# Install project dependencies
RUN npm install

# Default command to run your Selenium tests using xvfb
ENTRYPOINT ["xvfb-run", "sh", "-c"]
CMD ["node test_form_submit.js && node test_other_test.js"]
