# Dockerfile.tests
FROM node:14
RUN apt-get update && \
    apt-get install -y wget unzip xvfb libfontconfig \
    && wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && dpkg -i google-chrome*.deb; apt-get -f install -y \
    && rm google-chrome*.deb
RUN npm install -g selenium-webdriver chromedriver
WORKDIR /tests
COPY tests/selenium /tests
ENTRYPOINT ["xvfb-run", "node"]
CMD ["test_homepage.js", "&&", "node", "test_add_item.js"]
